name: rbc
description: "Role-based offline Chatbot"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.10.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  sqflite: ^2.3.0
  path: ^1.8.3
  provider: ^6.0.5
  cupertino_icons: ^1.0.8
  flutter_secure_storage: ^8.1.0
  http: ^1.1.0
  llama_cpp_dart: ^0.1.2+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:

  uses-material-design: true

  assets:
    
    - assets/prompts/doctor_prompt.txt
    - assets/prompts/nurse_prompt.txt
    - assets/prompts/patient_prompt.txt
